# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 03:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('plot_num', models.CharField(max_length=30)),
                ('property_name', models.CharField(max_length=30)),
                ('floor_num', models.IntegerField()),
                ('area_name', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Propertytype', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('max_area', models.DecimalField(decimal_places=15, max_digits=30)),
                ('min_budget', models.IntegerField()),
                ('max_budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Propertyy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('property_date', models.DateTimeField()),
                ('roomnum', models.IntegerField()),
                ('area', models.IntegerField()),
                ('priceper', models.DecimalField(decimal_places=15, max_digits=30)),
                ('property_add_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('propertyy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Propertyy')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propertyy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Propertyy')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('usertype', models.CharField(choices=[('B', 'Buyer'), ('S', 'Seller'), ('D', 'Broker')], max_length=1)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42)),
                ('privatekey', models.CharField(max_length=64)),
                ('file', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.User')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.User'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.User'),
        ),
    ]
