# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 05:40
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propy', '0002_auto_20180320_0523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_vol', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('status', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(max_length=10)),
                ('contract_add', models.CharField(max_length=100)),
                ('Abi', models.TextField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_vol', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('status', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('date', models.DateTimeField(auto_now=True)),
                ('buyorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Buy')),
                ('sellorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Sale')),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Coin'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propy.Wallet'),
        ),
    ]
