# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propy', '0003_auto_20180320_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyy',
            old_name='property_add_id',
            new_name='property_add',
        ),
    ]
